baseURL = "http://paul.annesley.cc/"
languageCode = "en-us"
title = "paul.annesley.cc"
theme = "antifail"
pygmentsCodeFences = true

[blackfriday]
  extensions = ["hardLineBreak", "fencedCode"]
  plainIDAnchors = true
