# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "antifail"
license = "MIT"
licenselink = "https://github.com/pda/antifail.com/blob/master/themes/antifail/LICENSE"
description = ""
homepage = "http://antifail.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Paul Annesley"
  homepage = "http://antifail.com/"
